### ISSUE TITLE
Commands not detected by the bot

### ISSUE THREAD

**Issue by explowz** [nullworks/catbot-reverse-relay#1]
Maybe somebody will have the time to fix it? I dunno. It just doesn't detect any commands being sent to it.

**Comment by BenCat07** [comment]
Could you elaborate what you are doing? (Also this repo is kinda dead)

**Comment by explowz** [comment]
Yeah, I know it is, but it's a very nice feature to be able to send commands to your bots from Discord. I was wrong in the first description. I remember talking to you about this somewhere in September 2020. The relay detects the commands being sent into the special channel that it requires, but does not do anything other that that. There's also something wrong with the channel maybe, as it was sending some messaged to wrote in to test it in channels such as main and the special channel for the bot chat relay (https://github.com/nullworks/catbot-logbot).
